myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"

urlpatterns = [
    path('leaderboard/', views.leaderboard, name="leaderboard"),
    path('profile/', views.profile, name="profile" ),
    path('', views.index, name="dashboard"),
    path('error/', views.error, name="error"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('add_profile/', views.add_profile, name="add_profile"),
    path('register/', views.register, name="register"),
]

ojproj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('root/', admin.site.urls),
    path('', include('myapp.urls', namespace="myapp")),
    path('admin/', include('adminsapp.urls', namespace="adminsapp"))
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Student(models.Model):
    user = models.OneToOneField(
        User, verbose_name="user", on_delete=models.CASCADE)
    code_chef_handle = models.CharField(max_length=150)
    hacker_rank_handle = models.CharField(max_length=150, blank=True)
    hacker_earth_handle = models.CharField(max_length=150, blank=True)
    code_forces_handle = models.CharField(max_length=150, blank=True)

    code_chef_score = models.IntegerField(blank=True, default=0)
    hacker_rank_score = models.IntegerField(blank=True, default=0)
    hacker_earth_score = models.IntegerField(blank=True, default=0)
    code_forces_score = models.IntegerField(blank=True, default=0)
    roll_no = models.CharField(max_length=10)
    branch = models.CharField(max_length=4)
    is_blocked = models.BooleanField(default=False)

    @property
    def total_score(self):
        return self.code_chef_score + self.hacker_rank_score + self.hacker_earth_score + self.code_forces_score

    def __str__(self) -> str:
        return self.roll_no

myapp/forms.py
from django import forms
from .models import Student
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    email = forms.CharField(label="Username", required=True)
    password = forms.CharField(
        label="Password", widget=forms.PasswordInput, required=True)


class UserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ["first_name", "last_name", "username" , "email", "password"]


class StudentForm(forms.Form):
    code_chef_handle = forms.CharField(label="code_chef_handle", required=True)
    hacker_rank_handle = forms.CharField(label="hacker_rank_handle", required=False)
    code_forces_handle = forms.CharField(label="code_forces_handle", required=False)
    hacker_earth_handle = forms.CharField(label="hacker_earth_handle", required=False)
    roll_no = forms.CharField(label="roll_no", required=True)
    branch = forms.CharField(label="branch", required=True)

myapp/views.py
from django.contrib.auth.models import User
from django.http.request import HttpRequest
from django.db.models import F
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from .forms import LoginForm, UserForm, StudentForm
from .models import Student


# Create your views here.
def leaderboard(req: HttpRequest):
    if not req.user.is_authenticated:
        return redirect('myapp:login')

    student: Student = Student.objects.get(user=req.user)
    students = Student.objects.filter(
        roll_no__startswith=student.roll_no[:2]
    ).annotate(total=F('code_chef_score') + F('code_forces_score') + F('hacker_rank_score') + F('hacker_earth_score')).order_by('-total')[:10]
    

    return render(req, "myapp/leaderboard.html", {"student": student, "students": students})


def index(req: HttpRequest):
    if not req.user.is_authenticated:
        return redirect('myapp:login')

    student: Student = Student.objects.get(user=req.user)

    return render(req, "myapp/dashboard.html", {"student": student})


def profile(req: HttpRequest):
    if not req.user.is_authenticated:
        return redirect('myapp:login')

    student = Student.objects.get(user=req.user)
    all_filled = False

    if(student.code_chef_handle == "" or student.code_forces_handle == "" or student.hacker_rank_handle == "" or student.hacker_earth_handle == ""):
        all_filled = True
    return render(req, "myapp/profile.html", {"student": student, "all_filled": all_filled})


def error(req):
    return render(req, "myapp/404.html")



def login(request: HttpRequest):
    if request.method == 'GET':
        return render(request, "myapp/login.html", {"form": LoginForm})
    if request.method == 'POST':
        username = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect("myapp:dashboard")
        else:
            return render(request, "myapp/login.html", {"form": LoginForm(request.POST)})


def add_profile(request: HttpRequest):
    platform = request.POST.get("platform")
    handle = request.POST.get("handle")
    if not request.user.is_authenticated:
        return redirect('myapp:login')

    student: Student = Student.objects.get(user=request.user)

    if(platform == "Code Forces"):
        student.code_forces_handle = handle
        student.save(update_fields=["code_forces_handle"])
    elif(platform == "Hacker Rank"):
        student.hacker_rank_handle = handle
        student.save(update_fields=["hacker_rank_handle"])
    elif(platform == "Hacker Earth"):
        student.hacker_earth_handle = handle
        student.save(update_fields=["hacker_earth_handle"])

    return redirect("myapp:profile")


def logout(req):
    auth_logout(req)
    return redirect("myapp:login")



def register(req :HttpRequest):
    if req.method == 'GET':
        user_form = UserForm()
        student_form = StudentForm()
        return render(req, "myapp/register.html")
    if req.method == 'POST':
        user_form = UserForm(req.POST)
        student_form = StudentForm(req.POST)
        if user_form.is_valid() and student_form.is_valid():
            # TODO save models

            user = User.objects.create(**user_form.cleaned_data)
            user.save()

            auth_login(req, user)

            student = Student.objects.create(
                user = user, 
                code_chef_handle = student_form.cleaned_data["code_chef_handle"], 
                code_forces_handle = student_form.cleaned_data["code_forces_handle"],
                hacker_rank_handle = student_form.cleaned_data["hacker_rank_handle"],
                hacker_earth_handle = student_form.cleaned_data["hacker_earth_handle"],
                roll_no = student_form.cleaned_data["roll_no"]
            )

            student.save()
            
            return redirect("myapp:dashboard")
        
        else:
            print(student_form.is_valid())
            print(student_form.errors)
            print(user_form.is_valid())

            context  = {
                "user_form":user_form,
                "student_form":student_form

            }
            return render(req, "myapp/register.html", context )

myapp/templates/myapp/dashboard.html
{% extends 'myapp/template.html' %} {% block body %}
<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="page-breadcrumb bg-white">
  <div class="row align-items-center">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h4 class="page-title">Dashboard</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
      <div class="d-md-flex">
        <ol class="breadcrumb ms-auto">
          <li><a href={% url 'myapp:dashboard' %} class="fw-normal">Dashboard</a></li>
        </ol>
      </div>
    </div>
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
  <!-- ============================================================== -->
  <!-- Three charts -->
  <!-- ============================================================== -->
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-12">
      <div class="white-box analytics-info">
        <h3 class="box-title">Hackerrank Score</h3>
        <ul class="list-inline two-part d-flex align-items-center mb-0">
          <li>
            <div id="sparklinedash">
              <canvas
                width="67"
                height="30"
                style="
                  display: inline-block;
                  width: 67px;
                  height: 30px;
                  vertical-align: top;
                "
              ></canvas>
            </div>
          </li>
          <li class="ms-auto"><span class="counter text-success">{{student.hacker_rank_score}} </span></li>
        </ul>
      </div>
    </div>
    <div class="col-lg-4 col-md-12">
      <div class="white-box analytics-info">
        <h3 class="box-title">Code Chef Score</h3>
        <ul class="list-inline two-part d-flex align-items-center mb-0">
          <li>
            <div id="sparklinedash2">
              <canvas
                width="67"
                height="30"
                style="
                  display: inline-block;
                  width: 67px;
                  height: 30px;
                  vertical-align: top;
                "
              ></canvas>
            </div>
          </li>
          <li class="ms-auto"><span class="counter text-purple">{{ student.code_chef_score }}</span></li>
        </ul>
      </div>
    </div>
    <div class="col-lg-4 col-md-12">
      <div class="white-box analytics-info">
        <h3 class="box-title">Code Forces Score</h3>
        <ul class="list-inline two-part d-flex align-items-center mb-0">
          <li>
            <div id="sparklinedash3">
              <canvas
                width="67"
                height="30"
                style="
                  display: inline-block;
                  width: 67px;
                  height: 30px;
                  vertical-align: top;
                "
              ></canvas>
            </div>
          </li>
          <li class="ms-auto"><span class="counter text-info">{{student.code_forces_score }}</span></li>
        </ul>
      </div>
    </div>
    <div class="col-lg-4 col-md-12">
      <div class="white-box analytics-info">
        <h3 class="box-title">Hacker Earth Score</h3>
        <ul class="list-inline two-part d-flex align-items-center mb-0">
          <li>
            <div id="sparklinedash3">
              <canvas
                width="67"
                height="30"
                style="
                  display: inline-block;
                  width: 67px;
                  height: 30px;
                  vertical-align: top;
                "
              ></canvas>
            </div>
          </li>
          <li class="ms-auto"><span class="counter text-info">{{student.hacker_earth_score }}</span></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  
  <!-- ============================================================== -->
  <!-- RECENT SALES -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
  <!-- Recent Comments -->
  <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Container fluid  -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- footer -->
<!-- ============================================================== -->
<footer class="footer text-center">
  2021 © Ample Admin brought to you by
  <a href="https://www.wrappixel.com/">wrappixel.com</a>
</footer>
<!-- ============================================================== -->
<!-- End footer -->
<!-- ============================================================== -->

{% endblock body %}

myapp/templates/myapp/leaderboard.html
{% extends 'myapp/template.html' %} {% block body %}

<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="page-breadcrumb bg-white">
  <div class="row align-items-center">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h4 class="page-title">Leader Board</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
      <div class="d-md-flex">
        <ol class="breadcrumb ms-auto">
          <li><a href="#" class="fw-normal">Dashboard</a></li>
        </ol>
      </div>
    </div>
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
  <!-- ============================================================== -->
  <!-- Start Page Content -->
  <!-- ============================================================== -->
  <div class="row">
    <div class="col-sm-12">
      <div class="white-box">
        <h3 class="box-title">Top 10 performers of your batch</h3>
        <p class="text-muted">Based on <code>score</code></p>
        <div class="table-responsive">
          <table class="table text-nowrap">
            <thead>
              <tr>
                <th class="border-top-0">Rank</th>
                <th class="border-top-0">First Name</th>
                <th class="border-top-0">Last Name</th>
                <th class="border-top-0">Username</th>
                <th class="border-top-0">Score</th>
              </tr>
            </thead>
            <tbody>
              {% for stud in students %}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{stud.user.first_name}}</td>
                <td>{{stud.user.last_name}}</td>
                <td>{{stud.user.username}}</td>
                <td>{{stud.total_score}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

myapp/templates/myapp/login.html
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OJ Manager Login</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href={% static "myapp/plugins/images/favicon.png"%}>
    <!-- Custom CSS -->
   <link href={% static "myapp/css/style.min.css" %} rel="stylesheet">

    <style>
      body {
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-align: center;
        -ms-flex-pack: center;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    </style>
  </head>

  <body class="text-center">

  
  <form action={% url 'myapp:login' %} method="post" class="form-signin">
      <img class="mb-4" src={% static 'myapp/plugins/images/vmeg-logo.jpg' %} alt="vardhaman logo" width="72">
      <h1 class="h3 mb-3 font-weight-normal">Log in</h1>
      <h2 class="h2 mb-3 text-muted">Vardhaman OJ Manager</h2>
      
      {% csrf_token %}
      
      {{form |crispy}}
      
      <button class="btn btn-primary btn-block w-100" type="submit">Log in</button>

    <a class="text-primary font-weight-bolder text-decoration-none" href={% url 'myapp:register' %}>Don't have an account?<span class="text-secondary"> Register<span></a>
    </form>




    <script src={% static "myapp/plugins/bower_components/jquery/dist/jquery.min.js" %}></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src={% static "myapp/bootstrap/dist/js/bootstrap.bundle.min.js" %}></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
        $(".preloader").fadeOut();
    </script>
  </body>
</html>

myapp/templates/myapp/profile.html
{% extends 'myapp/template.html' %} {% load static %} {% block body %}

<!-- ============================================================== -->
<!-- Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<div class="page-breadcrumb bg-white">
  <div class="row align-items-center">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
      <h4 class="page-title">Profile page</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
      <div class="d-md-flex">
        <ol class="breadcrumb ms-auto">
          <li><a href="#" class="fw-normal">Dashboard</a></li>
        </ol>
      </div>
    </div>
  </div>
  <!-- /.col-lg-12 -->
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Container fluid  -->
<!-- ============================================================== -->
<div class="container-fluid">
  <!-- ============================================================== -->
  <!-- Start Page Content -->
  <!-- ============================================================== -->
  <!-- Row -->
  <div class="row">
    <!-- Column -->
    <div class="col-lg-4 col-xlg-3 col-md-12">
      <div class="white-box">
        <div class="user-bg">
          <img width="100%" alt="user" src={% static
          "myapp/plugins/images/large/img1.jpg"%} />
          <div class="overlay-box">
            <div class="user-content">
              <a href="javascript:void(0)"
                ><img src={% static "myapp/plugins/images/users/1.jpg" %}
                class="thumb-lg img-circle" alt="img" /></a
              >
              <h4 class="text-white mt-2">{{request.user.username}}</h4>
              <h5 class="text-white mt-2">{{request.user.email}}</h5>
            </div>
          </div>
        </div>
        <div class="user-btm-box mt-5 d-md-flex">
          <div class="col-md-4 col-sm-4 text-center">
            <h1>{{student.roll_no}}</h1>
          </div>
        </div>
      </div>
    </div>
    <!-- Column -->
    <!-- Column -->
    <div class="col-lg-8 col-xlg-9 col-md-12">
      <div class="card">
        <div class="card-body">
          <form class="form-horizontal form-material">
            <div class="mb-4">
              <label class="col-md-12 p-0">Full Name</label>
              <div class="col-md-12 border-bottom p-0">
                <input
                  readonly
                  type="text"
                  value="{{request.user.first_name |upper }} {{request.user.last_name |upper }}"
                  class="form-control p-0 border-0"
                />
              </div>
            </div>
            <div class="mb-4">
              <label for="example-email" class="col-md-12 p-0"
                >Vardhaman Mail</label
              >
              <div class="col-md-12 border-bottom p-0">
                <input
                  readonly
                  type="email"
                  value={{student.user.email}}
                  class="form-control p-0 border-0"
                  name="example-email"
                  id="example-email"
                />
              </div>
            </div>
            <div class="mb-4">
              <label class="col-md-12 p-0">Roll No</label>
              <div class="col-md-12 border-bottom p-0">
                <input
                  readonly
                  type="text"
                  value={{student.roll_no}}
                  class="form-control p-0 border-0"
                />
              </div>
            </div>
            
          </form>
          {% if  all_filled %}
        <form action={% url 'myapp:add_profile' %} method = POST class="form-horizontal form-material">
          {% csrf_token %}

          <div class="form-group mb-4">
              <label class="col-sm-12">Add Other Platform</label>

              <div class="col-sm-12 border-bottom">
                <select
                  class="form-select shadow-none p-0 border-0 form-control-line"
                  name="platform"
                >
                {% if  student.code_chef_handle == "" %}
                  <option>Code Chef</option>
                {% endif %}
                {% if  student.code_forces_handle == "" %}
                  <option>Code Forces</option>
                {% endif %}
                {% if  student.hacker_rank_handle == "" %}
                  <option>Hacker Rank</option>
                {% endif %}
                {% if  student.hacker_earth_handle == "" %}
                  <option>Hacker Earth</option>
                {% endif %}
                </select>
              </div>
            </div>
            <div class="form-group mb-4">
              <label class="col-md-12 p-0">handle</label>
              <div class="col-md-12 border-bottom p-0">
                <input
                  type="text"
                  placeholder="Your Handle"
                  class="form-control p-0 border-0"
                  name="handle"
                />
              </div>
            </div>
            <div class="form-group mb-4">
              <div class="col-sm-12">
                <button class="btn btn-success">Add Profile</button>
              </div>
            </div>
        </form>
            {% endif %}
          <a href={% url 'myapp:logout' %} class="btn btn-danger">Logout</a>
        </div>
      </div>
    </div>
    <!-- Column -->
  </div>
  <!-- Row -->
  <!-- ============================================================== -->
  <!-- End PAge Content -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
  <!-- Right sidebar -->
  <!-- ============================================================== -->
  <!-- .right-sidebar -->
  <!-- ============================================================== -->
  <!-- End Right sidebar -->
  <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Container fluid  -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- footer -->
<!-- ============================================================== -->
<footer class="footer text-center">
  2021 © Ample Admin brought to you by
  <a href="https://www.wrappixel.com/">wrappixel.com</a>
</footer>
<!-- ============================================================== -->
<!-- End footer -->
<!-- ============================================================== -->

{% endblock body %}

myapp/templates/myapp/register.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OJ Manager Register</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href={% static "myapp/plugins/images/favicon.png"%}>
    <!-- Custom CSS -->
   <link href={% static "myapp/css/style.min.css" %} rel="stylesheet">


  </head>
<body class="">

      <div class="container">
      <div class="py-5 text-center bg-light text-dark">
        <img class="d-block mx-auto mb-4" src={% static 'myapp/plugins/images/vmeg-logo.jpg' %} alt="" width="72" height="72">
        <h2>Registration form</h2>
        

        {{user_form.errors}}
        {{student_form.errors}}
        
      </div>
        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Details</h4>
          <form method="POST" action= {% url 'myapp:register' %} >
          {% csrf_token %}
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="firstName">First name</label>
                <input type="text" class="form-control" id="firstName" placeholder="" required name="first_name">
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="lastName">Last name</label>
                <input type="text" class="form-control" id="lastName" placeholder="" required name="last_name">
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>
            </div>

            <div class="mb-3">
              <label for="username">Username</label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">@</span>
                </div>
                <input type="text" class="form-control" id="username" placeholder="Username" required name="username">
                <div  class="mx-3 text-muted">
                  Remember Your Username it will be used for your login
                </div>
                <div class="invalid-feedback" style="width: 100%;">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="mb-3">
              <label for="email">Email</label>
              <input type="email" class="form-control" id="email" placeholder="you@vardhaman.org" required name="email">
              <div  class="mx-2 text-muted">
                  Enter Vardhaman Mail ID only.
              </div>
              <div class="invalid-feedback">
                Please enter a valid email address.
              </div>
            </div>
            
            <div class="mb-3">
              <label for="Password">Password</label>
              <input type="Password" class="form-control" id="Password"  required name="password">
              <div  class="mx-2 text-muted">
                  Enter Password.
              </div>
            </div>

            <div class="mb-3">
              <label for="address">Codechef Username/handle</label>
              <input type="text" class="form-control"  placeholder="" required n name="code_chef_handle">
              <div class="invalid-feedback">
                Codechef Username/handle
              </div>
        
            </div>

            <div class="mb-3">
              <label for="codeforces">Codeforces Username<span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" id="codeforces" name="code_forces_handle">
            </div><div class="mb-3">
              <label for="hackerrank">Hackerrank Username<span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" id="hackerrank" name="hacker_rank_handle" >
            </div><div class="mb-3">
              <label for="hackerearth">Hackerearth Username<span class="text-muted">(Optional)</span></label>
              <input type="text" class="form-control" id="hackerearth" name="hacker_earth_handle">
            </div>

            
              <div class="col-md-3 mb-3">
                <label for="zip">Roll Number</label>
                <input type="text" class="form-control"  placeholder="1*881A0***" required name="roll_no">
                <div class="invalid-feedback">
                  Roll Number required.
                </div>
              </div>
              <div class="col-md-3 mb-3">
                <label for="branch">Branch</label>
                <select id="branch" class="form-control" required>
                  <option selected >----</option>
                  <option value="CSE">CSE</option>
                  <option value="ECE">ECE</option>
                  <option value="IT">IT</option>
                  <option value="EEE">EEE</option>
                  <option value="MECH">MECH</option>
                  <option value="CIVIL">CIVIL</option>
                </select>
              </div>
            </div>
            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Register</button>
          </form>
        </div>
      </div>
    </div>
    

    












  

  <script src={% static "myapp/plugins/bower_components/jquery/dist/jquery.min.js" %}></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src={% static "myapp/bootstrap/dist/js/bootstrap.bundle.min.js" %}></script>
    
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
        $(".preloader").fadeOut();
    </script>
</body>
</html>



 {% comment %} <form action= {% url 'myapp:register'  %} method='post'>
    {% csrf_token %}
    {{form |crispy }}
  </form> {% endcomment %}